[package]
name = "libzcashlc"
version = "0.0.2"
authors = ["Jack Grigg <jack@z.cash>",
            "Francisco Gindre <francisco@z.cash>",
]
edition = "2018"
build = "rust/build.rs"

[dependencies]
failure = "0.1"
ffi_helpers = "0.1"
hex = "0.3"

[dependencies.ff]
git = "https://github.com/str4d/librustzcash.git"
rev = "52d8b436300724bc4b83aa4a0c659ab34c3dbce7"

[dependencies.pairing]
git = "https://github.com/str4d/librustzcash.git"
rev = "52d8b436300724bc4b83aa4a0c659ab34c3dbce7"

[dependencies.zcash_client_backend]
git = "https://github.com/str4d/librustzcash.git"
rev = "52d8b436300724bc4b83aa4a0c659ab34c3dbce7"

[dependencies.zcash_client_sqlite]
git = "https://github.com/str4d/librustzcash.git"
rev = "52d8b436300724bc4b83aa4a0c659ab34c3dbce7"

[dependencies.zcash_primitives]
git = "https://github.com/str4d/librustzcash.git"
rev = "52d8b436300724bc4b83aa4a0c659ab34c3dbce7"

[dependencies.zcash_proofs]
git = "https://github.com/str4d/librustzcash.git"
rev = "52d8b436300724bc4b83aa4a0c659ab34c3dbce7"
default-features = false
features = ["local-prover"]

[build-dependencies]
cbindgen = "0.8"

[lib]
name = "zcashlc"
path = "rust/src/lib.rs"
crate-type = ["staticlib"]

[profile.release]
lto = true

[features]
mainnet = ["zcash_client_sqlite/mainnet"]